name: Rclone Backups

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  backup:
    name: Backup rclone drives
    runs-on: ubuntu-latest
    env:
      RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          token: ${{ secrets.GH_PAT }}

      - name: Backup Immich
        run: |
          echo "Backing up Immich to backups"
          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.IMMICH_SOURCE }} ${{ secrets.BACKUPS_DEST }}/immich
          if [ $? -ne 0 ]; then
            echo "Error backing up immich to backups"
            exit 1
          fi

      - name: Backup Nextcloud
        run: |
          echo "Backing up Nextcloud to backups"
          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.NEXTCLOUD_SOURCE }} ${{ secrets.BACKUPS_DEST }}/nextcloud
          if [ $? -ne 0 ]; then
            echo "Error backing up nextcloud to backups"
            exit 1
          fi

      - name: Update Rclone config
        uses: AnimMouse/setup-rclone/update-config@v1
        with:
          rclone_config_secret_name: ${{ secrets.RCLONE_CONFIG }}
          token: ${{ secrets.GH_PAT }}
